name: Build Test Deploy 1.5

on:
  push:
    branches: [ "1.5" ]
  pull_request:
    branches: [ "1.5" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          cache: 'maven'
          server-id: sonatype-nexus-snapshots
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Build with Maven and Gradle
        run: |
          ./mvnw -B -Dhttps.protocols=TLSv1.2 verify --file pom.xml
          export MY_POM_VERSION=`./mvnw -q -Dexec.executable="echo" -Dexec.args='${projects.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec`
          echo "POM VERSION" ${MY_POM_VERSION}
          if [[ $MY_POM_VERSION =~ ^.*SNAPSHOT$ ]];
          then
              ./mvnw -B -Dhttps.protocols=TLSv1.2 clean deploy
          else
              echo "not deploying release: " ${MY_POM_VERSION}
          fi
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
